version: "3.1"

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    environment:
      - LOGSPOUT=ignore
      - cluster.name=docker-cluster
      - network.host=0.0.0.0
      - discovery.zen.minimum_master_nodes=1
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.ml.enabled=false
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
        memlock:
            soft: -1
            hard: -1
        nofile:
            soft: 65536
            hard: 65536
    deploy:
        restart_policy:
            delay: 5s
        mode: replicated
        replicas: 1
    networks:
      - elk
      - monitoring_monitoring

  logstash:
    image: docker.elastic.co/logstash/logstash:5.4.0
    command: 'logstash -e ''input { udp { port => 5000 codec => json } } output { elasticsearch { hosts => ["elasticsearch:9200"] } stdout { codec => rubydebug } }'''
    ports:
      - 5000:5000
    environment:
       DEBUG:                  "${LOGSTASH_DEBUG:-false}"
       LOGSPOUT:               ignore
       ELASTICSEARCH_USER:     ${ELASTICSEARCH_LOGS_USER}
       ELASTICSEARCH_PASSWORD: ${ELASTICSEARCH_LOGS_PASSWORD}
       ELASTICSEARCH_SSL:      ${ELASTICSEARCH_LOGS_SSL}
       ELASTICSEARCH_ADDR:     ${ELASTICSEARCH_LOGS_ADDR:-elasticsearch}
       ELASTICSEARCH_PORT:     ${ELASTICSEARCH_LOGS_PORT:-9200}
    networks:
      - elk
      - monitoring_monitoring
    deploy:
        mode: replicated
        replicas: 2
        resources:
            limits:
                cpus: '0.25'
                memory: 800M
            reservations:
                cpus: '0.25'
                memory: 400M

  kibana:
    image: docker.elastic.co/kibana/kibana:5.4.0
    ports:
      - "5601:5601"
    networks:
      - elk
    environment:
        - LOGSPOUT=ignore
        - ELASTICSEARCH_URL=http://elasticsearch:9200
        - NODE_OPTIONS=--max-old-space-size=200
    deploy:
        mode: replicated
        replicas: 1
        resources:
            limits:
                cpus: '0.25'
                memory: 384M
            reservations:
                cpus: '0.25'
                memory: 256M

  logspout:
     image: bekt/logspout-logstash:latest
     networks:
         - elk
     volumes:
         - /var/run/docker.sock:/var/run/docker.sock
     environment:
         ROUTE_URIS: logstash://logstash:5000
         DOCKER_LABELS: "true"
     deploy:
         mode: global
         restart_policy: 
           delay: 5s
         resources:
             limits:
                 cpus: '0.25'
                 memory: 64M
             reservations:
                 cpus: '0.25'
                 memory: 32M

  curator:
         image: akailash/curator_30d
         networks:
             - elk
         environment:
             HOST: elasticsearch
             PORT: 9200
             COMMAND: "curator --config /etc/curator/config.yml /etc/curator/action_file.yml"
             PREFIX: logstash-
             DAYS:    30
             SCHEDULE: "0 0 0 * * ?"
         deploy:
             mode: replicated
             replicas: 1


networks:
  elk:
  monitoring_monitoring:
      external: true
volumes:
    elasticsearch-data:
        driver: "rexray"
