version: "3.1"

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - LOGSPOUT=ignore
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS-Xmx512m -Xms512m"
    ulimits:
        memlock:
            soft: -1
            hard: -1
        nofile:
            soft: 65536
            hard: 65536
    deploy:
        mode: replicated
        replicas: 1
        resources:
            limits:
                cpus: '2'
                memory: 640M
            reservations:
                cpus: '0.5'
                memory: 512M
    networks:
      - elk
      - monitoring_monitoring

  logstash:
    image: docker.elastic.co/logstash/logstash:5.4.0
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5000:5000"
    environment:
       DEBUG:                  "${LOGSTASH_DEBUG:-false}"
       LOGSPOUT:               ignore
       ELASTICSEARCH_USER:     ${ELASTICSEARCH_LOGS_USER}
       ELASTICSEARCH_PASSWORD: ${ELASTICSEARCH_LOGS_PASSWORD}
       ELASTICSEARCH_SSL:      ${ELASTICSEARCH_LOGS_SSL}
       ELASTICSEARCH_ADDR:     ${ELASTICSEARCH_LOGS_ADDR:-elasticsearch}
       ELASTICSEARCH_PORT:     ${ELASTICSEARCH_LOGS_PORT:-9200}
    networks:
      - elk
    deploy:
        mode: replicated
        replicas: 2
        resources:
            limits:
                cpus: '0.25'
                memory: 800M
            reservations:
                cpus: '0.25'
                memory: 400M

  kibana:
    image: docker.elastic.co/kibana/kibana:5.4.0
    volumes:
      - ./kibana/config/:/usr/share/kibana/config
    ports:
      - "5601:5601"
    networks:
      - elk
    environment:
        - LOGSPOUT=ignore
        - ELASTICSEARCH_URL=http://elasticsearch:9200
    deploy:
        mode: replicated
        replicas: 1
        resources:
            limits:
                cpus: '0.25'
                memory: 384M
            reservations:
                cpus: '0.25'
                memory: 256M

 logspout:
     image: bekt/logspout-logstash:latest
     networks:
         - logging
     volumes:
         - /var/run/docker.sock:/var/run/docker.sock
     environment:
         ROUTE_URIS: logstash://logstash:5000
         DOCKER_LABELS: "true"
     deploy:
         mode: global
         resources:
             limits:
                 cpus: '0.25'
                 memory: 64M
             reservations:
                 cpus: '0.25'
                 memory: 32M

networks:
  elk:
    driver: overlay
  monitoring_monitoring:
      external: true
volumes:
    elasticsearch-data:
        external: true

